// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbsqlc

type Documents struct {
	ID        int64
	Content   []byte
	CreatedAt int64
}

type Metadatas struct {
	ID         int64
	ObjectID   *int64
	Key        string
	Value      string
	CreatedAt  int64
	DocumentID *int64
}

type Migration struct {
	ID        int64
	CreatedAt int64
	Version   int64
}

type S3Objects struct {
	ID        int64
	Bucket    string
	Key       string
	CreatedAt int64
}
