// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID        pgtype.UUID
	Content   []byte
	CreatedAt int64
}

type Metadata struct {
	ObjectID   pgtype.UUID
	DocumentID pgtype.UUID
	Key        string
	Value      string
	CreatedAt  int64
}

type Migration struct {
	ID        int64
	CreatedAt int64
	Version   int64
}

type S3Object struct {
	ID        pgtype.UUID
	Bucket    string
	Key       string
	CreatedAt int64
}
