// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: s3_object.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const s3ObjectFindById = `-- name: S3ObjectFindById :one
SELECT id, created_at
FROM s3_objects
WHERE id = $1
`

func (q *Queries) S3ObjectFindById(ctx context.Context, db DBTX, id pgtype.UUID) (*S3Object, error) {
	row := db.QueryRow(ctx, s3ObjectFindById, id)
	var i S3Object
	err := row.Scan(&i.ID, &i.CreatedAt)
	return &i, err
}

const s3ObjectInsert = `-- name: S3ObjectInsert :one
INSERT INTO s3_objects DEFAULT VALUES RETURNING id, created_at
`

func (q *Queries) S3ObjectInsert(ctx context.Context, db DBTX) (*S3Object, error) {
	row := db.QueryRow(ctx, s3ObjectInsert)
	var i S3Object
	err := row.Scan(&i.ID, &i.CreatedAt)
	return &i, err
}
